mysite/honoradar/urls.py
from django.urls import path

from . import views

app_name = 'honoradar'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('senddata/', views.senddata, name='senddata')

]

mysite/mysite/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('honoradar/', include('honoradar.urls')),
    path('admin/', admin.site.urls),
]

mysite/honoradar/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        was_published_recently.admin_order_field = 'pub_date'
        was_published_recently.boolean = True
        was_published_recently.short_description = 'Published recently?'
    list_filter = ['pub_date']
    search_fields = ['question_text']

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class form(models.Model):
    pass


class Medium(models.Model):
    form = models.ForeignKey(form, on_delete=models.CASCADE)
    medium_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    list_filter = ['pub_date']
    search_fields = ['medium_text']
    pass

class Salary(models.Model):
    form = models.ForeignKey(form, on_delete=models.CASCADE)
    salary_number=models.IntegerField()

class Rating(models.Model):
    form = models.ForeignKey(form, on_delete=models.CASCADE)
    salary_number=models.IntegerField()

mysite/honoradar/views.py
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic

from .models import Question, Choice

def senddata(request):
    print("senddata")
    print(request.POST.get('mediumname'))
    return HttpResponseRedirect(reverse('honoradar:index'))

class IndexView(generic.ListView):
    template_name = 'honoradar/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'honoradar/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'honoradar/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'honoradar/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('honoradar:results', args=(question.id,)))

mysite/honoradar/templates/honoradar/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'honoradar:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

mysite/honoradar/templates/honoradar/index_safety.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'honoradar/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
<li><a href="{% url 'honoradar:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/honoradar/templates/honoradar/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'honoradar:detail' question.id %}">Vote again?</a>